### ISSUE TITLE
App crashes.

### ISSUE THREAD

**Issue by Dynnaro** [FreeiamHQ/bugs-and-ideas#24]
App crashes after going throught a **Path** -happened _2_ times- for whatever reason.

**Comment by michavie** [comment]
- which path(s)? every path?
- when just scrolling? on the top, on the bottom of the path?
- or when liking, or starting a challenge?

**Comment by michavie** [comment]
can not reproduce after many attemps; if you encounter it again, please follow up with reproduction steps 🙏
