### ISSUE TITLE
App is slow and laggy.

### ISSUE THREAD

**Issue by Dynnaro** [FreeiamHQ/bugs-and-ideas#25]
App is faster than before _but no so much_  which results in non working nice features like confetti popping when _100_ is completed 

Phone : Samsung A10
full specification : https://www.gsmarena.com/samsung_galaxy_a10-9580.php (2GB version)

**Comment by michavie** [comment]
confetti is probably the most resource-intensive feature of the app, where the intensity increases with the amount of confetti used. the next release (2.3.10) will use a reduced amount of confetti as an attempt to fix/improve this

**Comment by Dynnaro** [comment]
Roger that
